apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "zookeeper-deployment-config-jhye"
  namespace: "default"
  labels:
    app: "zookeeper-deployment"
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
