version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    platform: linux/arm64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - peer-prep-network

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: broker
    platform: linux/arm64
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: always
    networks:
      - peer-prep-network

  matching:
    build: ./backend/matching
    container_name: matching-container
    ports:
      - "3002:3002"
    env_file:
      - ./backend/matching/.env
    volumes:
      - ./backend/matching/src:/app/src
    depends_on:
      - kafka
    networks:
      - peer-prep-network

  matchverification:
    build: ./backend/matchverification
    container_name: match-verification-container
    ports:
      - "3006:3006"
    env_file:
      - ./backend/matchverification/.env
    volumes:
      - ./backend/matchverification/src:/app/src
    depends_on:
      - matching
    networks:
      - peer-prep-network

  collaboration:
    build: ./backend/collaboration
    container_name: collaboration-container
    ports:
      - "3001:3001"
    volumes:
      - ./backend/collaboration:/app
      - /app/node_modules
    env_file:
      - ./backend/collaboration/.env
    networks:
      - peer-prep-network

  signaling:
    build: ./backend/signaling
    container_name: signaling-container
    ports:
      - "4444:4444"
    volumes:
      - ./backend/signaling:/app
      - /app/node_modules
    networks:
      - peer-prep-network

  websocket:
    build: ./backend/websocket
    container_name: websocket-container
    ports:
      - "3005:3005"
    env_file:
      - ./backend/websocket/.env
    volumes:
      - ./backend/websocket/src:/app/src
    networks:
      - peer-prep-network

  websocketchat:
    build: ./backend/websocketchat
    container_name: websocket-chat-container
    ports:
      - "3007:3007"
    env_file:
      - ./backend/websocketchat/.env
    volumes:
      - ./backend/websocketchat/src:/app/src
    networks:
      - peer-prep-network

  chatlogs:
    build: ./backend/chatlog
    container_name: chatlog
    ports:
      - "3008:3008"
    env_file:
      - ./backend/chatlog/.env
    volumes:
      - ./backend/chatlog:/app
      - /app/node_modules
    networks:
      - peer-prep-network

  redis:
    image: redis:6.2.6
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - peer-prep-network

  question:
    build: ./backend/question
    container_name: question-container
    ports:
      - "3003:3003"
    volumes:
      - ./backend/question:/app
      - /app/node_modules
    env_file:
      - ./backend/question/.env
    networks:
      - peer-prep-network

  user:
    build: ./backend/user
    container_name: user-container
    ports:
      - "3004:3004"
    volumes:
      - ./backend/user:/app
      - /app/node_modules
    env_file:
      - ./backend/user/.env
    networks:
      - peer-prep-network

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - peer-prep-network

volumes:
  mongo-data:

networks:
  peer-prep-network:
