apiVersion: v1
kind: Service
metadata:
  name: matching
  namespace: default
spec:
  selector:
    app: matching-deployment
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
