apiVersion: v1
kind: Service
metadata:
  name: signaling
  namespace: default
spec:
  selector:
    app: signaling-deployment
  ports:
  - protocol: TCP
    port: 32624 # Port exposed by the service
    targetPort: 32634 # Port exposed by the pod
    nodePort: 32624
  type: LoadBalancer
