apiVersion: v1
kind: Service
metadata:
  name: signaling
  namespace: default
spec:
  selector:
    app: signaling-deployment
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
  type: ClusterIP
