apiVersion: v1
kind: Service # Expose the service to be accessible from outside the cluster
metadata:
  name: haproxy-ingress-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    run: haproxy-ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
