apiVersion: networking.k8s.io/v1
kind: Ingress # route external traffic into the cluster
metadata:
  name: haproxy-ingress
  namespace: default
  annotations:
    haproxy.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /collaboration(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: collaboration-service
            port:
              number: 3001
      - path: /matching
        pathType: Prefix
        backend:
          service:
            name: matching-service
            port:
              number: 3002
      - path: /question(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: question-service
            port:
              number: 3003

      - path: /user(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3004
