apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "websocket-deployment-config-jhye"
  namespace: "default"
  labels:
    app: "websocket-deployment"
data:
  FRONTEND_CORS_ALLOWED_ORIGINS: "https://frontend-2-598285527681.us-central1.run.app/"
  ENV: "DEV"
  DEV_REDIS_HOST: "redis"
  DEV_REDIS_PORT: "6379"
  DEV_KAFKA_URL: "kafka-service:9092"
  DEV_QUESTION_API_URL: "http://question:3003/api/question"
