apiVersion: v1
kind: Service
metadata:
  name: websocket
  namespace: default
spec:
  selector:
    app: websocket-deployment
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
  type: ClusterIP
