apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kafka-deployment"
  namespace: "default"
  labels:
    app: "kafka-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kafka-deployment"
  template:
    metadata:
      labels:
        app: "kafka-deployment"
    spec:
      containers:
      - name: "kafka-service-sha256-1"
        image: "confluentinc/cp-kafka:7.7.1"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: "KAFKA_BROKER_ID"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_BROKER_ID"
              name: "kafka-deployment-config-jhye"
        - name: "KAFKA_ZOOKEEPER_CONNECT"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_ZOOKEEPER_CONNECT"
              name: "kafka-deployment-config-jhye"
        - name: "KAFKA_LISTENERS"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_LISTENERS"
              name: "kafka-deployment-config-jhye"
        - name: "KAFKA_ADVERTISED_LISTENERS"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_ADVERTISED_LISTENERS"
              name: "kafka-deployment-config-jhye"
        - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
          valueFrom:
            configMapKeyRef:
              key: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
              name: "kafka-deployment-config-jhye"
