apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "collaboration-deployment"
  namespace: "default"
  labels:
    app: "collaboration-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "collaboration-deployment"
  template:
    metadata:
      labels:
        app: "collaboration-deployment"
    spec:
      containers:
      - name: "collaboration-service-sha256-1"
        image: "gcr.io/peerprep-backend/collaboration@sha256:ec34095fbe88708081620a1df6453bc246e662260e43b4b1e3422671f7e3d4eb"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: "MONGODB_URI"
          valueFrom:
            configMapKeyRef:
              key: "MONGODB_URI"
              name: "collaboration-deployment-config-jhye"
        - name: "NODE_ENV"
          valueFrom:
            configMapKeyRef:
              key: "NODE_ENV"
              name: "collaboration-deployment-config-jhye"
