apiVersion: v1
kind: Service
metadata:
  name: collaboration
  namespace: default
spec:
  selector:
    app: collaboration-deployment
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
