apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
  labels:
    app: frontend-deployment
spec:
  selector:
    app: frontend-deployment
  type: LoadBalancer
  ports:
  - port: 80 # External port that will be exposed
    targetPort: 8080 # Internal port the container listens to (adjust as needed)
    protocol: TCP
