apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "frontend-deployment"
  namespace: "default"
  labels:
    app: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend-deployment"
  template:
    metadata:
      labels:
        app: "frontend-deployment"
    spec:
      containers:
      - name: "frontend-service-sha256-1"
        image: "us-central1-docker.pkg.dev/peerprep-backend/cloud-run-source-deploy/cs3\
          219-ay2425s1-project-g15/frontend-2@sha256:28b4a786c63a09ce349593fdca\
          18640897ea659734bfefcaf9f1239ee094548b"
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
