apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: websocketchat-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocketchat-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: websocketchat-server-sha256-1
      controlledResources: [ "cpu", "memory" ]
      minAllowed:
        cpu: 100m
        memory: 100Mi
      maxAllowed:
        cpu: 1000m
        memory: 1Gi
      controlledValues: "Values"
      updateMode: "Auto"
      useRestarts: true
      useScaleDown: true
      useScaleUp: true
      useUpdate: true
      useVolumeResize: true
      volumePolicies: []
