apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "websocketchat-deployment"
  namespace: "default"
  labels:
    app: "websocketchat-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websocketchat-deployment"
  template:
    metadata:
      labels:
        app: "websocketchat-deployment"
    spec:
      containers:
      - name: "websocketchat-service-sha256-1"
        image: "gcr.io/peerprep-backend/websocketchat@sha256:1e1aa8623c0f8c00be36b502e4\
          39fb7428bf422db86546f847284433a9be9fe1"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        # allow the exposed ingress to access the service
        - name: "FRONTEND_CORS_ALLOWED_ORIGINS"
          value: "http://35.202.162.147/"
