apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "websocketchat-deployment"
  namespace: "default"
  labels:
    app: "websocketchat-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websocketchat-deployment"
  template:
    metadata:
      labels:
        app: "websocketchat-deployment"
    spec:
      containers:
      - name: "websocketchat-service-sha256-1"
        image: "gcr.io/peerprep-backend/websocketchat@sha256:8aa1a999db4b9a97cff5af6d0c304e7c9a866e4592cf58a3bfc2c3dff86d67a5"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        # allow the exposed ingress to access the service
        - name: "FRONTEND_CORS_ALLOWED_ORIGINS"
          value: "*"
