apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "websocketchat-deployment"
  namespace: "default"
  labels:
    app: "websocketchat-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websocketchat-deployment"
  template:
    metadata:
      labels:
        app: "websocketchat-deployment"
    spec:
      containers:
      - name: "websocketchat-service-sha256-1"
        image: "gcr.io/peerprep-backend/websocketchat@sha256:84f0bf6d19fd4880f2ae59af89\
          ea70019a6187d07f259827161b14110bf1ec06"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        # allow the exposed ingress to access the service
        - name: "FRONTEND_CORS_ALLOWED_ORIGINS"
          value: "http://35.202.162.147/"
