apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "websocketchat-deployment"
  namespace: "default"
  labels:
    app: "websocketchat-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "websocketchat-deployment"
  template:
    metadata:
      labels:
        app: "websocketchat-deployment"
    spec:
      containers:
      - name: "websocketchat-service-sha256-1"
        image: "gcr.io/peerprep-backend/websocketchat@sha256:7ffe1df99b6df065c596f7a48ab336cc3a1654be46ce35b625e299992ee6a9a0"
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: "FRONTEND_CORS_ALLOWED_ORIGINS"
          value: "http://35.184.99.208/match"
