apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    app: user-deployment
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
  type: ClusterIP
