apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "user-deployment"
  namespace: "default"
  labels:
    app: "user-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "user-deployment"
  template:
    metadata:
      labels:
        app: "user-deployment"
    spec:
      containers:
      - name: "user-service-sha256-1"
        image: "gcr.io/peerprep-backend/user@sha256:ab1bc25c0c8375a9336f58a5eb3d2e10b8c\
          c682abff8967bf9899bf9ecbe2da7"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3004
        livenessProbe:
          httpGet:
            path: /api/iam
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/iam
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: "DB_CLOUD_URI"
          valueFrom:
            configMapKeyRef:
              key: "DB_CLOUD_URI"
              name: "user-deployment-config-jhye"
        - name: "ENV"
          valueFrom:
            configMapKeyRef:
              key: "ENV"
              name: "user-deployment-config-jhye"
        - name: "JWT_SECRET"
          valueFrom:
            configMapKeyRef:
              key: "JWT_SECRET"
              name: "user-deployment-config-jhye"
        - name: "EMAIL_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "EMAIL_PASSWORD"
              name: "user-deployment-config-jhye"
        - name: "FRONTEND_URL"
          valueFrom:
            configMapKeyRef:
              key: "FRONTEND_URL"
              name: "user-deployment-config-jhye"
        - name: "credentials_type"
          valueFrom:
            configMapKeyRef:
              key: "credentials_type"
              name: "user-deployment-config-jhye"
        - name: "credentials_project_id"
          valueFrom:
            configMapKeyRef:
              key: "credentials_project_id"
              name: "user-deployment-config-jhye"
        - name: "credentials_private_key_id"
          valueFrom:
            configMapKeyRef:
              key: "credentials_private_key_id"
              name: "user-deployment-config-jhye"
        - name: "credentials_private_key"
          valueFrom:
            configMapKeyRef:
              key: "credentials_private_key"
              name: "user-deployment-config-jhye"
        - name: "credentials_client_email"
          valueFrom:
            configMapKeyRef:
              key: "credentials_client_email"
              name: "user-deployment-config-jhye"
        - name: "credentials_client_id"
          valueFrom:
            configMapKeyRef:
              key: "credentials_client_id"
              name: "user-deployment-config-jhye"
        - name: "credentials_auth_uri"
          valueFrom:
            configMapKeyRef:
              key: "credentials_auth_uri"
              name: "user-deployment-config-jhye"
        - name: "credentials_token_uri"
          valueFrom:
            configMapKeyRef:
              key: "credentials_token_uri"
              name: "user-deployment-config-jhye"
        - name: "credentials_auth_provider"
          valueFrom:
            configMapKeyRef:
              key: "credentials_auth_provider"
              name: "user-deployment-config-jhye"
        - name: "credentials_cert_url"
          valueFrom:
            configMapKeyRef:
              key: "credentials_cert_url"
              name: "user-deployment-config-jhye"
